name: Reusable E2E Test Workflow

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r e2e_tests/requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Wait for backend
        run: python wait_for_backend.py

      - name: Run Playwright tests
        run: pytest e2e_tests/
