---
name: Agent Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  agent-interaction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Environment
        run: cp .env.example .env

      - name of: Start Backend Services (retry)
        run: |
          set -euo pipefail
          for i in 1 2 3; do
            docker compose up --build -d backend postgres redis && break || sleep $((i*10))
          done

      - name: Run Jules Agent
        run: docker compose run jules

      - name: Run Ana Agent (Conflict Test)
        run: >
          docker compose run --entrypoint
          "python agents/efai-agent/efaiagent.py intent
          --files agents/verifieragent.py
          --branch agent/ana/test
          --summary 'Ana testing'" jules

      - name: Emit Planner Checkpoint on Failure
        if: failure()
        run: >
          python cirecoveryengine/plannercheckpointemitter.py
          --job agent-interaction --out planner_checkpoint.json

      - name: Emit Debug Event
        if: failure()
        run: >
          python cirecoveryengine/debugeventemitter.py
          --job agent-interaction --out debug_event.json

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: ci-diagnostics
          path: |
            planner_checkpoint.json
            debug_event.json
            docker-pull-logs.txt
