name: Citation Sync

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly

jobs:
  sync-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Sync citations
        run: python -m agents.jules.cli sync-zotero --api-key ${{ secrets.ZOTERO_API_KEY }} --user ${{ secrets.ZOTERO_USER_ID }} --collections "My Library"
