name: Jules Docker CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/reusable/lint.yml

  unit-test:
    uses: ./.github/workflows/reusable/unit-test.yml

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c5b6b7f3c8c7e3f6d9a1e3b1f2a3c4d5e6f7a8b9

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Jules container
        id: build-push
        uses: docker/build-push-action@9e436ba7d6c8e4d6b4e2d1a8bce2b6a3be5b6b2c
        with:
          context: .
          push: true
          tags: ghcr.io/virtualframes/jules:latest
          provenance: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes "ghcr.io/virtualframes/jules@${{ steps.build-push.outputs.digest }}"

      - name: Run smoke test
        run: |
          docker run --rm ghcr.io/virtualframes/jules:latest echo "Jules container validated"
