name: LangChain Audit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Set up Python
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Download NLTK data
        run: python -m nltk.downloader punkt
      - name: Run LangChain audit
        env:
          NLTK_DATA: /home/runner/nltk_data
        run: python -m agents.jules.cli summarize --docs notebooks/research/example_reproducible.ipynb --prompt "Summarize this notebook."
