name: LangChain Audit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r agents/jules/requirements.txt
      - name: Download NLTK data
        run: python -c "import nltk; nltk.download('punkt')"
      - name: Run LangChain audit
        env:
          NLTK_DATA: /home/runner/nltk_data
        run: python agents/jules/cli.py summarize --docs notebooks/research/example_reproducible.ipynb --prompt "Summarize this notebook."
